### ISSUE TITLE
ux/ui

### ISSUE THREAD

**Issue by gitRoee** [JacksonVirgo/discord-mafia-archive#4]

**Comment by gitRoee** [comment]
i will see if i have time for my hobbies soon
prob no
if so i will start in two weeks and design the site
basically, the idea that it's an archive, right?
anyway it at least should be planned like forums so there is more room to learn about that.
the first idea to come to mind is to have it with just one section called "archives".
i have old plannings for a forum design i remember. that should make it easier.
@JacksonVirgo

**Comment by JacksonVirgo** [comment]
I don't really feel making it forum-like is the way to go, as it's message data and it wouldn't entirely make sense to do that rather than just make it load like a messaging app, that you can't send messages in.

**Comment by gitRoee** [comment]
i mean there are no other options
